// <auto-generated />
using BlueBank.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlueBank.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210325203642_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlueBank.Models.Cuenta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreTitular")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("saldo")
                        .HasColumnType("int");

                    b.Property<int>("valorConsignar")
                        .HasColumnType("int");

                    b.Property<int>("valorInicial")
                        .HasColumnType("int");

                    b.Property<int>("valorRetirar")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Cuenta");
                });
#pragma warning restore 612, 618
        }
    }
}
